# Generated by Django 6.0 on 2026-02-06 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitems',
            old_name='subtotal',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='order',
            name='points_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='store_credit_used',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total antes de impuestos', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='total_tax',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total de impuestos (IVA)', max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitems',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Monto de IVA de este ítem', max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='final_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total final con impuestos', max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CARD', 'Tarjeta'), ('CASH', 'Efectivo'), ('STORE_CREDIT', 'Crédito Tienda'), ('LOYALTY_POINTS', 'Puntos')], max_length=20),
        ),
    ]
