# Generated by Django 6.0 on 2026-01-24 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PAID', 'Pagado'), ('PENDING', 'Pendiente'), ('CANCELED', 'Cancelado')], default='PAID', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='ticket_folio',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
