# Generated by Django 6.0 on 2026-02-08 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_subtotal_orderitems_amount_order_points_used_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
    ]
