# Generated by Django 6.0 on 2026-02-09 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CARD', 'Tarjeta'), ('CASH', 'Efectivo'), ('STORE_CREDIT', 'Crédito Tienda'), ('LOYALTY_POINTS', 'Puntos')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PAID', 'Pagado'), ('PENDING', 'Pendiente'), ('CANCELED', 'Cancelado')], default='PENDING', max_length=20),
        ),
    ]
