# Generated by Django 6.0 on 2026-01-26 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_discount_applied_order_final_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='money_saved_total',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Monto total ahorrado (Suma de descuentos)', max_digits=10),
        ),
    ]
