# Generated by Django 6.0 on 2026-02-05 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='tax_rate',
            field=models.CharField(choices=[('16.00', 'Tasa General (16%)'), ('8.00', 'Tasa Fronteriza (8%)'), ('0.00', 'Tasa del 0%'), ('EXENT', 'Exento')], default='16.00', max_length=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
