# Generated by Django 6.0 on 2026-01-14 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='promotion',
            table='PROMOTIONS  ',
        ),
    ]
