# Generated by Django 6.0 on 2026-01-22 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_promotion_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='target_audience',
            field=models.CharField(choices=[('ALL', 'Todos los clientes'), ('FREQUENT_ONLY', 'Cliente frecuente')], max_length=30),
        ),
        migrations.AlterModelTable(
            name='promotion',
            table='PROMOTIONS',
        ),
    ]
