# Generated by Django 6.0 on 2026-02-11 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_discounted_price_alter_product_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='active_promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_on_products', to='products.promotion'),
        ),
        migrations.AddField(
            model_name='product',
            name='promo_requires_frequent_customer',
            field=models.BooleanField(default=False, help_text='Si está activo, solo aplica para clientes marcados como frecuentes.'),
        ),
    ]
