# Generated by Django 6.0 on 2026-02-17 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_active_promotion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='min_stock',
        ),
        migrations.AddField(
            model_name='product',
            name='low_stock',
            field=models.BooleanField(default=False),
        ),
    ]
