# Generated by Django 6.0 on 2026-02-01 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('birth_date', models.DateField()),
                ('is_frequent', models.BooleanField(default=False)),
                ('current_points', models.IntegerField(default=0)),
                ('last_status_check', models.DateField(blank=True, null=True)),
                ('last_birthday_discount_year', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'CUSTOMERS',
            },
        ),
        migrations.CreateModel(
            name='PointsTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('transaction_type', models.CharField(choices=[('EARN', 'Ganancia por compra'), ('REDEEM', 'Canjeo de puntos'), ('ADJUSTMENT', 'Ajuste manual'), ('EXPIRED', 'Expiración de puntos')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='customers.customer')),
            ],
        ),
    ]
