# Generated by Django 6.0 on 2026-01-22 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_phone_number'),
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='current_points',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PointsTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('transaction_type', models.CharField(choices=[('EARN', 'Ganancia por compra'), ('REDEEM', 'Canjeo de puntos'), ('ADJUSTMENT', 'Ajuste manual'), ('EXPIRED', 'Expiración de puntos')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='customers.customer')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order')),
            ],
        ),
    ]
