# Generated by Django 6.0 on 2026-01-25 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_current_points_pointstransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='last_status_check',
            field=models.DateField(blank=True, null=True),
        ),
    ]
