# Generated by Django 6.0 on 2026-01-26 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customer_last_status_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='last_birthday_discount_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
