# Generated by Django 6.0 on 2026-01-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatBotUsers',
            fields=[
                ('mobile_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('last_interaction', models.DateTimeField()),
            ],
        ),
    ]
