# Generated by Django 6.0 on 2026-02-01 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatBotUsers',
            fields=[
                ('mobile_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('last_interaction', models.DateTimeField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'CHATBOT_USERS',
            },
        ),
    ]
