# Generated by Django 6.0 on 2026-01-26 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbotusers',
            name='last_interaction',
            field=models.DateTimeField(blank=True, default=None),
        ),
    ]
