# Generated by Django 6.0 on 2026-01-26 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_alter_chatbotusers_last_interaction'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='chatbotusers',
            table='CHATBOT_USERS',
        ),
    ]
