# Generated by Django 6.0 on 2026-01-14 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=20)),
                ('contact_person', models.CharField(max_length=40)),
                ('rfc', models.CharField(max_length=40)),
                ('tax_address', models.CharField(verbose_name=250)),
            ],
            options={
                'db_table': 'SUPPLIERS',
            },
        ),
    ]
