# Generated by Django 6.0 on 2026-01-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='mobile_number',
            new_name='phone_number',
        ),
        migrations.AlterField(
            model_name='supplier',
            name='tax_address',
            field=models.CharField(max_length=250),
        ),
    ]
